# Generated by Django 3.0.7 on 2021-01-18 23:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0003_auto_20210118_2312'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='StudentFile1',
            new_name='StudentFileDOY',
        ),
        migrations.RenameField(
            model_name='studentfiledoy',
            old_name='file1',
            new_name='fileDOY',
        ),
        migrations.RenameField(
            model_name='studentfiledoy',
            old_name='file1_date_uploaded',
            new_name='fileDOY_date_uploaded',
        ),
        migrations.CreateModel(
            name='StudentFileID',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fileID', models.FileField(blank=True, null=True, upload_to='students/file1/')),
                ('fileID_date_uploaded', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='StudentFileIBAN',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fileIBAN', models.FileField(blank=True, null=True, upload_to='students/file1/')),
                ('fileIBAN_date_uploaded', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='StudentFileEFKA',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fileEFKA', models.FileField(blank=True, null=True, upload_to='students/file1/')),
                ('fileEFKA_date_uploaded', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
