# Generated by Django 3.0.7 on 2021-01-19 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20210119_1356'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Schools',
            new_name='School',
        ),
    ]
