# Generated by Django 3.0.7 on 2021-01-19 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20210119_1401'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='title',
            field=models.CharField(max_length=60),
        ),
    ]
